### PR TITLE
Improvements to CSS

### PR DESCRIPTION
**Pull request by choldgraf**
This PR does the following:

Theme HTML
* Adds the HTML templating to add "previous" and "next" buttons - we use this template in several other themes (e.g: https://github.com/jupyterhub/mybinder.org-deploy/blob/master/docs/source/_templates/page.html) so this just standardizes this.

Theme CSS:
* Updates the CSS on these buttons to make them a bit more "button-ey"
* Freezes the left sidebar in place so that you can scroll it independently from the main content (similar to how the RTD theme does)
* Adds a default Jupyter logo in case no other logo is specified
* Removes the first H2 in the right sidebar because it's just page title and probably not useful for a TOC

Theme-demo:
* Adds some lorem ipsum to make it easier to demo content/navigation/etc

latest version: https://51-153355305-gh.circle-artifacts.com/0/html/index.html
Demo GIF:

### CODE REVIEW

**Comment by choldgraf** [comment]
Preview here: https://41-153355305-gh.circle-artifacts.com/0/html/index.html

Would love comments from the @jupyterhub/jupyterhubteam :-)

**Comment by ryanlovett** [comment]
As an end user I like these changes! One issue: I vertically shrunk a browser window with the example you linked to so that the table of contents was clipped, however I couldn't scroll it. I was just curious to see how the sidebar scrolling would present itself. (Chrome/Mac)

**Comment by choldgraf** [comment]
@ryanlovett hmmm that's a good point, I *think* that this would be fixed by setting a height for the div of the sidebar. Could you try this again with the latest build and see if it works now?

https://45-153355305-gh.circle-artifacts.com/0/html/index.html

**Comment by parente** [comment]
I was able to horizontally scroll the main body text underneath the nav bar in Firefox in the latest change. That's probably a consequence of the fixed sidebar, but a solid white sidebar background might make the behavior less confusing.

Screen Shot 2019-04-10 at 11 26 23 PM

**Comment by ryanlovett** [comment]
@choldgraf That fixes it for me, thanks!

I also get the horizontal behavior reported by @parente, but in Chrome.

**Comment by choldgraf** [comment]
Good catch @parente and thanks for following up @ryanlovett. I think I fixed the horizontal CSS bug here:

https://47-153355305-gh.circle-artifacts.com/0/html/index.html

does that work?

**Comment by ryanlovett** [comment]
Looks great. The only issue I can find is that text is clipped when the window is at its narrowest. I thought this might be only relevant for people who are providing feedback on UI issues [ :) ] but it is also present on mobile (Android/Chrome). Just fyi -- I don't really look at this sort of material on small screens that often.

Desktop
Screen Shot 2019-04-12 at 12 31 59 PM

Mobile
Screenshot (Apr 12, 2019 12_38_01 PM)

**Comment by choldgraf** [comment]
Good catch once again! Fixed in the latest push (I believe)

https://49-153355305-gh.circle-artifacts.com/0/html/index.html

**Comment by parente** [comment]
LGTM

**Comment by choldgraf** [comment]
would love thoughts from @willingc if she has a moment!

**Comment by ryanlovett** [comment]
Spotted this:
Screen Shot 2019-04-16 at 10 19 26 AM

When the window is wide enough to have the TOC and text be side-by-side, but narrow enough to need the horizontal scroll bar, the text can be made to move over the TOC by scrolling.

**Comment by choldgraf** [comment]
good catch again - I made the background of the sidebar white so that it blocks the overlapping text in case this particular screen size is there. That work?

latest version: https://51-153355305-gh.circle-artifacts.com/0/html/index.html

Anybody else from @jupyterhub/jupyterhubteam have thoughts on this?

**Comment by ryanlovett** [comment]
Nice, that's it from me!

**Review by minrk — APPROVED** [review]

**Comment by betatim** [comment]
Looks good!

I am a big fan of https://khan.github.io/tota11y/ (only draw back of it is that I can't work out how to use it in Firefox where I use a custom theme to remove UI elements and hence have no working bookmark bar :(). It points out a few things that we could address in small issues (tagged as "help wanted") or do a bigger PR.

The reason I looked at the page with it was that I wanted to know what the faded "Next" buttons looked like contrast wise. Personal taste would be not to have them so "invisible" and then darker on hover but always dark and without the border around them. For a new PR though.

**Pull request merged**
